# Generated by Django 3.0.8 on 2020-08-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(max_length=264, unique=True),
        ),
    ]
